---

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  command: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Ensure Drupal directory exists.
  file:
    path: /var/www/html/drupal
    state: directory
    owner: apache
    group: apache

- name: Check if Drupal project already exists.
  stat:
    path: "/var/www/html/drupal/composer.json"
  register: drupal_composer_json

- name: Create Drupal project.
  composer:
    command: create-project
    arguments: drupal/recommended-project /var/www/html/drupal
    working_dir: /var/www/html/drupal
    no_dev: true

- name: Add drush to the Drupal site with Composer.
  composer:
    command: require
    arguments: drush/drush:10.*
    working_dir: /var/www/html/drupal
  become_user: root
  
- name: Create settings.php
  copy:
    src: /var/www/html/drupal/web/sites/default/default.settings.php 
    dest: /var/www/html/drupal/web/sites/default/settings.php
    mode: 0777

- name: Set permissions on files directory.
  file:
    path: "/var/www/html/drupal/web/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes

- name: Install Drupal.
  shell:
      vendor/bin/drush si -y --site-name="Drupal 9 with ANSIBLE" 
      --account-name=admin 
      --account-pass=admin 
      --db-url=mysql://root:123@localhost/ansible_drupal9 
      --root=/var/www/html/drupal/
      chdir=/var/www/html/drupal 
      creates=/var/www/html/drupal/sites/default/settings.php
  args:
    executable: /bin/bash
  
- name: restart httpd
  service: 
    name: httpd 
    state: restarted


  












    


